apiVersion: v1
kind: configMap
metaData:
  name: learner-jobs-config
  labels:
    app: flink
data:
  user-cache-config.yaml: |+
    kafka.brokers-servers: "localhost:9092"
    kafka.zookeeper: "localhost:2181"
