version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: git submodule update --init
      - run: git submodule update --init --recursive --remote
      - restore_cache:
          key: lms-dependency-cache-{{ checksum "pom.xml" }}
      - run: mvn clean package -Dmaven.test.skip=true
      - save_cache:
          key: lms-dependency-cache-{{ checksum "pom.xml" }}
          paths: ~/.m2

workflows:
  version: 2.1
  workflow:
    jobs:
      - build